# Generated by Django 5.0.4 on 2024-06-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id_enseigne', models.AutoField(db_column='ID_enseigne', primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, db_column='Libelle', max_length=127, null=True)),
                ('adresse', models.CharField(blank=True, db_column='Adresse', max_length=255, null=True)),
                ('adres_code_postal', models.IntegerField(blank=True, db_column='Adres_code_postal', null=True)),
                ('adres_commune', models.CharField(blank=True, db_column='Adres_commune', max_length=50, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=65535, max_digits=65535, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=65535, max_digits=65535, null=True)),
                ('date_creation_enseigne', models.DateField(blank=True, db_column='Date_creation_Enseigne', null=True)),
                ('date_modif_enseigne', models.DateField(blank=True, db_column='Date_modif_Enseigne', null=True)),
            ],
            options={
                'db_table': 'Enseigne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtatProduit',
            fields=[
                ('id_etat', models.AutoField(db_column='ID_etat', primary_key=True, serialize=False)),
                ('libelle_etat', models.CharField(blank=True, db_column='Libelle_etat', max_length=127, null=True)),
                ('date_creation_etat_produit', models.DateField(blank=True, db_column='Date_creation_Etat_Produit', null=True)),
                ('date_modif_etat_produit', models.DateField(blank=True, db_column='Date_modif_Etat_Produit', null=True)),
            ],
            options={
                'db_table': 'Etat_Produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrixProduitMagasin',
            fields=[
                ('id_prix_produit_magasin', models.AutoField(db_column='ID_prix_Produit_Magasin', primary_key=True, serialize=False)),
                ('prix', models.DecimalField(blank=True, db_column='Prix', decimal_places=65535, max_digits=65535, null=True)),
                ('date_creation_prix_produit_magasin', models.DateField(blank=True, db_column='Date_creation_prix_Produit_Magasin', null=True)),
                ('date_modif_prix_produit_magasin', models.DateField(blank=True, db_column='Date_modif_prix_Produit_Magasin', null=True)),
            ],
            options={
                'db_table': 'Prix_Produit_Magasin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(db_column='ID_produit', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('code_barre', models.CharField(blank=True, db_column='Code_barre', max_length=127, null=True)),
                ('tva', models.DecimalField(blank=True, db_column='TVA', decimal_places=65535, max_digits=65535, null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=127, null=True)),
                ('date_creation_produit', models.DateField(blank=True, db_column='Date_creation_Produit', null=True)),
                ('date_modif_produit', models.DateField(blank=True, db_column='Date_modif_Produit', null=True)),
            ],
            options={
                'db_table': 'Produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeUtilisateur',
            fields=[
                ('id_type_utilisateur', models.AutoField(db_column='ID_type_utilisateur', primary_key=True, serialize=False)),
                ('libelle_type', models.CharField(blank=True, db_column='Libelle_type', max_length=50, null=True)),
                ('date_creation_type_utilisateur', models.DateField(blank=True, db_column='Date_creation_Type_Utilisateur', null=True)),
                ('date_modif_type_utilisateur', models.DateField(blank=True, db_column='Date_modif_Type_Utilisateur', null=True)),
            ],
            options={
                'db_table': 'Type_Utilisateur',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Magasins',
        ),
        migrations.DeleteModel(
            name='Prixproduitsmagasins',
        ),
        migrations.DeleteModel(
            name='Produits',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='Categories',
        ),
        migrations.AlterModelTable(
            name='utilisateurs',
            table='Utilisateurs',
        ),
    ]
