# Generated by Django 5.0.4 on 2024-06-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0002_enseigne_etatproduit_prixproduitmagasin_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id_produit', models.AutoField(db_column='ID_produit', primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, db_column='Libelle', max_length=255, null=True)),
                ('libelle_ticket', models.CharField(blank=True, db_column='Libelle_Ticket', max_length=255, null=True)),
                ('prixttc', models.DecimalField(blank=True, db_column='PrixTTC', decimal_places=65535, max_digits=65535, null=True)),
                ('code_barre', models.CharField(blank=True, db_column='Code_barre', max_length=255, null=True)),
                ('tva', models.DecimalField(blank=True, db_column='TVA', decimal_places=65535, max_digits=65535, null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=255, null=True)),
                ('date_creation_produit', models.DateField(blank=True, db_column='Date_creation_Produit', null=True)),
                ('date_modif_produit', models.DateField(blank=True, db_column='Date_modif_Produit', null=True)),
            ],
            options={
                'db_table': 'Produits',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
